// Generated by gencpp from file move_canopy/MovePos.msg
// DO NOT EDIT!


#ifndef MOVE_CANOPY_MESSAGE_MOVEPOS_H
#define MOVE_CANOPY_MESSAGE_MOVEPOS_H

#include <ros/service_traits.h>


#include <move_canopy/MovePosRequest.h>
#include <move_canopy/MovePosResponse.h>


namespace move_canopy
{

struct MovePos
{

typedef MovePosRequest Request;
typedef MovePosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePos
} // namespace move_canopy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_canopy::MovePos > {
  static const char* value()
  {
    return "65467c40f11db30d3240bc807e76bdf9";
  }

  static const char* value(const ::move_canopy::MovePos&) { return value(); }
};

template<>
struct DataType< ::move_canopy::MovePos > {
  static const char* value()
  {
    return "move_canopy/MovePos";
  }

  static const char* value(const ::move_canopy::MovePos&) { return value(); }
};


// service_traits::MD5Sum< ::move_canopy::MovePosRequest> should match 
// service_traits::MD5Sum< ::move_canopy::MovePos > 
template<>
struct MD5Sum< ::move_canopy::MovePosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_canopy::MovePos >::value();
  }
  static const char* value(const ::move_canopy::MovePosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_canopy::MovePosRequest> should match 
// service_traits::DataType< ::move_canopy::MovePos > 
template<>
struct DataType< ::move_canopy::MovePosRequest>
{
  static const char* value()
  {
    return DataType< ::move_canopy::MovePos >::value();
  }
  static const char* value(const ::move_canopy::MovePosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_canopy::MovePosResponse> should match 
// service_traits::MD5Sum< ::move_canopy::MovePos > 
template<>
struct MD5Sum< ::move_canopy::MovePosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_canopy::MovePos >::value();
  }
  static const char* value(const ::move_canopy::MovePosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_canopy::MovePosResponse> should match 
// service_traits::DataType< ::move_canopy::MovePos > 
template<>
struct DataType< ::move_canopy::MovePosResponse>
{
  static const char* value()
  {
    return DataType< ::move_canopy::MovePos >::value();
  }
  static const char* value(const ::move_canopy::MovePosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_CANOPY_MESSAGE_MOVEPOS_H
