// Generated by gencpp from file move_canopy/MovePosResponse.msg
// DO NOT EDIT!


#ifndef MOVE_CANOPY_MESSAGE_MOVEPOSRESPONSE_H
#define MOVE_CANOPY_MESSAGE_MOVEPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_canopy
{
template <class ContainerAllocator>
struct MovePosResponse_
{
  typedef MovePosResponse_<ContainerAllocator> Type;

  MovePosResponse_()
    : reached(false)  {
    }
  MovePosResponse_(const ContainerAllocator& _alloc)
    : reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reached_type;
  _reached_type reached;





  typedef boost::shared_ptr< ::move_canopy::MovePosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_canopy::MovePosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MovePosResponse_

typedef ::move_canopy::MovePosResponse_<std::allocator<void> > MovePosResponse;

typedef boost::shared_ptr< ::move_canopy::MovePosResponse > MovePosResponsePtr;
typedef boost::shared_ptr< ::move_canopy::MovePosResponse const> MovePosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_canopy::MovePosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_canopy::MovePosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_canopy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_canopy::MovePosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_canopy::MovePosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_canopy::MovePosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_canopy::MovePosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_canopy::MovePosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_canopy::MovePosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_canopy::MovePosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80204a6ff2622a7071680d5597cbd3aa";
  }

  static const char* value(const ::move_canopy::MovePosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80204a6ff2622a70ULL;
  static const uint64_t static_value2 = 0x71680d5597cbd3aaULL;
};

template<class ContainerAllocator>
struct DataType< ::move_canopy::MovePosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_canopy/MovePosResponse";
  }

  static const char* value(const ::move_canopy::MovePosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_canopy::MovePosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reached\n\
";
  }

  static const char* value(const ::move_canopy::MovePosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_canopy::MovePosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovePosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_canopy::MovePosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_canopy::MovePosResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_CANOPY_MESSAGE_MOVEPOSRESPONSE_H
